export const LOAD_ITEMS = "LOAD_ITEMS";
export const ITEM_LOAD_FAILED = "ITEM_LOAD_FAILED";
export const SELECTED_ITEM = "SELECTED_ITEM";

export const LOAD_COMMENTS = "LOAD_COMMENTS";
export const COMMENT_LOAD_FAILED = "COMMENT_LOAD_FAILED";

export const LOAD_CATEGORIES = "LOAD_CATEGORIES";
export const CATEGORY_LOAD_FAILED = "CATEGORY_LOAD_FAILED";
export const SELECTED_CATEGORY = "SELECTED_CATEGORY";

export const COMMENT_SUBMIT_FAILED = "COMMENT_SUBMIT_FAILED";
export const COMMENT_SUBMIT_LOADING = "COMMENT_SUBMIT_LOADING";
export const COMMENT_SUBMIT_SUCCESS = "COMMENT_SUBMIT_SUCCESS";

export const TRY_SIGNUP = "TRY_SIGNUP";
export const TRY_LOGIN = "TRY_LOGIN";

export const AUTHENTICATE_USER = "AUTHENTICATE_USER"; 